version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
      - 8000:8000
    depends_on:
      - api
    networks:
      - botify
    volumes:
      # change to your static path
      - static:/home/ubuntu/app/chatty/chatty/static/
      - /etc/letsencrypt:/etc/letsencrypt
  django:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # set to your production settings file
      - DJANGO_SETTINGS_MODULE=config.production_settings
    command: >
      sh -c "
              python manage.py migrate && 
              python manage.py collectstatic --noinput &&
              daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - ./:/usr/src/config/
      - static:/usr/src/config/config/static/
    expose:
      - 8000
    networks:
      - config
  web:
    restart: always
    build:
      context: ./chatty/frontend/
      dockerfile: Dockerfile
    command: >
      sh -c "
             npm start"
    environment:
      - REACT_APP_BACKEND_URL=http://ec2-13-40-190-167.eu-west-2.compute.amazonaws.com:8000
      - REACT_APP_WS_URL=ws://ec2-13-40-190-167.eu-west-2.compute.amazonaws.com:8000
    volumes:
      - ./chatty/frontend:/usr/src/chatty/chatty/frontend
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - db3
    networks:
      - db-net3

networks:
  config:
    driver: bridge

volumes:
  static:


