version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    depends_on:
      - django
    networks:
      - db-net3
  django:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      
    user: ${CURRENT_UID}
    environment:
      # - change this to your settings file
      - DJANGO_SETTINGS_MODULE=config.settings
      - REACT_APP_DEV=1

    command: >
      sh -c "
              python manage.py migrate &&
              daphne -b 0.0.0.0 -p 8080 config.asgi:application"
    volumes:
      # change to your base directory
      - ./:/usr/src/chatty/
    ports:
      - 8080:8080
    env_file:
      # put the env fie in the same directory as the manage.py file
      - ./chatty/.env
    depends_on:
      - web
    networks:
      # create your own network
      - db-net3
  web:
    restart: always
    build:
      context: ./chatty/frontend/
      dockerfile: Dockerfile
    command: >
      sh -c "
             npm start"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - REACT_APP_WS_URL=ws://localhost:8080
    volumes:
      - ./chatty/frontend:/usr/src/chatty/chatty/frontend
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - db3
    networks:
      - db-net3
  db3:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./chatty/.env
    networks:
      # create your own network
      - db-net3
volumes:
  postgres_data:




networks:
  db-net3:
    driver: bridge
