version: '3.8'

services:
  redis:
      image: redis:alpine
      ports:
        - 6379:6379
      depends_on:
        - django
      networks:
        - config
  web:
      restart: always
      build:
        context: ./chatty/frontend/
        dockerfile: production/Dockerfile
      volumes:
        - ./chatty/frontend:/usr/src/chatty/chatty/frontend
        - react-build:/usr/src/chatty/chatty/frontend/build
      
      networks:
        - config
      ports:
        - 80:80
      stdin_open: true
  django:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # set to your production settings file
      - DJANGO_SETTINGS_MODULE=config.production_settings
      - REACT_APP_DEV=0
    command: >
      sh -c "
              python manage.py migrate && 
              python manage.py collectstatic --noinput &&
              daphne -b 0.0.0.0 -p 8080 config.asgi:application"
    volumes:
      - ./:/usr/src/chatty/
      - static:/usr/src/chatty/chatty/static/
    ports:
      - 8080:8080
    networks:
      - config
    depends_on:
      - web

networks:
  config:

volumes:
  static:
  react-build:


