version: '3.8'

services:
  django:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # set to your production settings file
      - DJANGO_SETTINGS_MODULE=config.production_settings
      - REACT_APP_DEV=0
    command: >
      sh -c "
              python manage.py migrate && 
              python manage.py collectstatic --noinput &&
              daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - ./:/usr/src/chatty/
      - static:/usr/src/chatty/chatty/static/
    expose:
      - 8000
    networks:
      - config
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/
    depends_on:
      - django
    environment:
      - REACT_APP_BACKEND_URL=http://ec2-13-40-190-167.eu-west-2.compute.amazonaws.com:8000
      - REACT_APP_WS_URL=ws://ec2-13-40-190-167.eu-west-2.compute.amazonaws.com:8000
    networks:
      - config

networks:
  config:

volumes:
  static:


